longNames = {
    "AAL": "American Airlines",
    "AAPL": "Apple",
    "AGNC": "AGNC Investment",
    "AMC": "AMC Entertainment",
    "AMD": "Advanced Micro Devices",
    "AMZN": "Amazon",
    "ASML": "ASML Holding",
    "ATKR": "Atkore",
    "BAC": "Bank of America",
    "BBBY": "Bed Bath & Beyond",
    "BBIO": "BridgeBio Pharma",
    "BLU": "BELLUS Health",
    "BMEA": "Biomea Fusion",
    "BSGA": "Blue Safari Group Acquisition",
    "CSCO": "Cisco",
    "CTRA": "Coterra Energy",
    "DKNG": "DraftKings",
    "ELYM": "Eliem Therapeutics",
    "ERIC": "Ericsson",
    "ETRN": "Equitrans Midstream",
    "EXTR": "Extreme Networks",
    "FDBC": "Fidelity D&D Bancorp",
    "FRC": "First Republic Bank",
    "GDEN": "Golden Entertainment",
    "GMDA": "Gamida Cell",
    "GMVD": "G Medical Innovations",
    "GNRC": "Generac",
    "GOOG": "Alphabet",
    "GRAB": "Grab Holdings",
    "GRIN": "Grindrod Shipping Holdings",
    "HAIA": "Healthcare AI Acquisition",
    "HBAN": "Huntington Bancshares",
    "HLMN": "Hillman Solutions",
    "HSAI": "Hesai Group",
    "HWCPZ": "Hancock Whitney",
    "HYFM": "Hydrofarm Holdings",
    "IMAQ": "International Media Acquisition",
    "INTC": "Intel",
    "IRMD": "iRadimed",
    "ISRG": "Intuitive Surgical",
    "JBLU": "JetBlue Airways",
    "LCID": "Lucid Group",
    "LUNR": "Intuitive Machines",
    "MRVL": "Marvell Technology",
    "MSFT": "Microsoft",
    "NFLX": "Netflix",
    "NIO": "Nio",
    "NVDA": "Nvidia",
    "PACW": "PacWest Bancorp",
    "PHYS": "Sprott Physical Gold Trust",
    "PSTX": "Poseida Therapeutics",
    "RBLX": "Roblox",
    "RIVN": "Rivian",
    "ROKU": "Roku",
    "RPHM": "Reneo Pharmaceuticals",
    "SCHW": "Charles Schwab",
    "SGHT": "Sight Sciences",
    "SNAP": "Snap",
    "STRO": "Sutro Biopharma",
    "TEAF": "Ecofin Sustainble",
    "TSLA": "Tesla",
    "UAL": "United Airlines",
    "UFAB": "Unique Fabricating",
    "ULBI": "Ultralife",
    "VALE": "Vale",
    "WAL": "Western Alliance",
    "XPEV": "XPeng",
    "XTNT": "Xtant Medical",
    "YCBD": "cbdMD",
}
print(len(longNames))